# driver_set().get
from Project_Data.function_open_driver import driver_set

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
import time
from selenium.webdriver.common.keys import Keys

# def test_login():
#     base_url = "https://portal-dev.safsarglobal.link/"
#     my_driver = driver_set()
#     my_driver.get(base_url)
#     time.sleep(3)
#     login_btn = my_driver.find_element(By.CSS_SELECTOR, "sm:flex hidden text-primaryLight hover:text-primaryPurple font-bold px-8 py-2" or By.href, "/signin")
#     login_btn.click()
#     time.sleep(3)

#####test-1.1.1
def test_login_proccess_edit_first_name_1_1_1():
    my_driver = driver_set()
    my_driver.get("https://portal-dev.safsarglobal.link/")
    login_header_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.LINK_TEXT, "התחברות")))
    time.sleep(2)
    login_header_element.click()
    phone_num_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.NAME, "phone")))
    phone_num_field_element.send_keys('0544803749')
    time.sleep(1)
    login_btn_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//button[contains(text(),'כניסה')]")))
    login_btn_element.click()
    WebDriverWait(my_driver, 30).until(EC.url_to_be("https://portal-dev.safsarglobal.link/"))
    time.sleep(5)
    my_account_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="root"]/div[1]/div/nav/div[1]/ul/button')))
    my_account_btn.click()
    time.sleep(2)
    edit_profile_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="rc-tabs-0-panel-tab1"]/div/div[1]/button')))
    edit_profile_btn.click()
    time.sleep(5)
    first_name_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.ID, "firstName")))
    first_name_field_element.send_keys(Keys.CONTROL + 'a')
    first_name_field_element.send_keys(Keys.BACKSPACE)
    time.sleep(2)
    first_name_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.ID, "firstName")))
    first_name_field_element.send_keys("נועה")
    time.sleep(3)
    attribute_first_name = first_name_field_element.get_attribute("defaultValue")
    assert attribute_first_name == 'נועה'
    save_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//body/div[@id='root']/main[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/form[1]/div[3]/div[1]/div[1]/div[1]/div[1]/button[1]")))
    save_btn.click()
    time.sleep(3)
    my_driver.close()
    my_driver.quit()


####test-1.1.2
def test_login_proccess_edit_last_name_1_1_2():
    my_driver = driver_set()
    my_driver.get("https://portal-dev.safsarglobal.link/")
    login_header_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.LINK_TEXT, "התחברות")))
    time.sleep(2)
    login_header_element.click()
    phone_num_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.NAME, "phone")))
    phone_num_field_element.send_keys('0544803749')
    time.sleep(1)
    login_btn_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//button[contains(text(),'כניסה')]")))
    login_btn_element.click()
    WebDriverWait(my_driver, 30).until(EC.url_to_be("https://portal-dev.safsarglobal.link/"))
    time.sleep(5)
    my_account_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="root"]/div[1]/div/nav/div[1]/ul/button')))
    my_account_btn.click()
    time.sleep(2)
    edit_profile_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="rc-tabs-0-panel-tab1"]/div/div[1]/button')))
    edit_profile_btn.click()
    last_name_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="lastName"]')))
    last_name_field_element.send_keys(Keys.CONTROL + 'a')
    last_name_field_element.send_keys(Keys.BACKSPACE)
    time.sleep(2)
    last_name_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="lastName"]')))
    last_name_field_element.send_keys("לוי")
    time.sleep(5)
    attribute_last_name = last_name_field_element.get_attribute("defaultValue")
    assert attribute_last_name == 'לוי'
    save_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//body/div[@id='root']/main[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/form[1]/div[3]/div[1]/div[1]/div[1]/div[1]/button[1]")))
    save_btn.click()
    time.sleep(3)
    my_driver.close()
    my_driver.quit()


####test-1.1.3
def test_login_proccess_edit_email_1_1_3():
    my_driver = driver_set()
    my_driver.get("https://portal-dev.safsarglobal.link/")
    login_header_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.LINK_TEXT, "התחברות")))
    time.sleep(2)
    login_header_element.click()
    phone_num_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.NAME, "phone")))
    phone_num_field_element.send_keys('0544803749')
    time.sleep(1)
    login_btn_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//button[contains(text(),'כניסה')]")))
    login_btn_element.click()
    WebDriverWait(my_driver, 30).until(EC.url_to_be("https://portal-dev.safsarglobal.link/"))
    time.sleep(5)
    my_account_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="root"]/div[1]/div/nav/div[1]/ul/button')))
    my_account_btn.click()
    time.sleep(2)
    edit_profile_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="rc-tabs-0-panel-tab1"]/div/div[1]/button')))
    edit_profile_btn.click()
    email_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="email"]')))
    email_field_element.send_keys(Keys.CONTROL + 'a')
    email_field_element.send_keys(Keys.BACKSPACE)
    time.sleep(2)
    email_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="email"]')))
    email_field_element.send_keys("jogog92125@artgulin.com")
    time.sleep(5)
    attribute_email = email_field_element.get_attribute("defaultValue")
    assert  attribute_email  == "jogog92125@artgulin.com"
    save_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//body/div[@id='root']/main[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/form[1]/div[3]/div[1]/div[1]/div[1]/div[1]/button[1]")))
    save_btn.click()
    time.sleep(3)
    my_driver.close()
    my_driver.quit()


####test-1.1.4
def test_login_proccess_edit_first_name_1_1_4():
    my_driver = driver_set()
    my_driver.get("https://portal-dev.safsarglobal.link/")
    login_header_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.LINK_TEXT, "התחברות")))
    time.sleep(2)
    login_header_element.click()
    phone_num_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.NAME, "phone")))
    phone_num_field_element.send_keys('0544803749')
    time.sleep(1)
    login_btn_element = WebDriverWait(my_driver, 10).until(
        EC.presence_of_element_located((By.XPATH, "//button[contains(text(),'כניסה')]")))
    login_btn_element.click()
    WebDriverWait(my_driver, 30).until(EC.url_to_be("https://portal-dev.safsarglobal.link/"))
    time.sleep(5)
    my_account_btn = WebDriverWait(my_driver, 10).until(
        EC.presence_of_element_located((By.XPATH, '//*[@id="root"]/div[1]/div/nav/div[1]/ul/button')))
    my_account_btn.click()
    time.sleep(2)
    edit_profile_btn = WebDriverWait(my_driver, 10).until(
        EC.presence_of_element_located((By.XPATH, '//*[@id="rc-tabs-0-panel-tab1"]/div/div[1]/button')))
    edit_profile_btn.click()
    time.sleep(5)
    first_name_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.ID, "firstName")))
    first_name_field_element.send_keys(Keys.CONTROL + 'a')
    first_name_field_element.send_keys(Keys.BACKSPACE)
    time.sleep(2)
    first_name_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.ID, "firstName")))
    first_name_field_element.send_keys("2")
    time.sleep(3)
    attribute_first_name = first_name_field_element.get_attribute("defaultValue")
    assert attribute_first_name == '2'
    save_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//body/div[@id='root']/main[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/form[1]/div[3]/div[1]/div[1]/div[1]/div[1]/button[1]")))
    save_btn.click()
    time.sleep(3)
    my_driver.close()
    my_driver.quit()

#####test-1.1.5
def test_login_proccess_edit_first_name_1_1_5():
    my_driver = driver_set()
    my_driver.get("https://portal-dev.safsarglobal.link/")
    login_header_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.LINK_TEXT, "התחברות")))
    time.sleep(2)
    login_header_element.click()
    phone_num_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.NAME, "phone")))
    phone_num_field_element.send_keys('0544803749')
    time.sleep(1)
    login_btn_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//button[contains(text(),'כניסה')]")))
    login_btn_element.click()
    WebDriverWait(my_driver, 30).until(EC.url_to_be("https://portal-dev.safsarglobal.link/"))
    time.sleep(5)
    my_account_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="root"]/div[1]/div/nav/div[1]/ul/button')))
    my_account_btn.click()
    time.sleep(2)
    edit_profile_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="rc-tabs-0-panel-tab1"]/div/div[1]/button')))
    edit_profile_btn.click()
    time.sleep(5)
    first_name_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.ID, "firstName")))
    first_name_field_element.send_keys(Keys.CONTROL + 'a')
    first_name_field_element.send_keys(Keys.BACKSPACE)
    time.sleep(2)
    first_name_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.ID, "firstName")))
    first_name_field_element.send_keys("!")
    time.sleep(3)
    attribute_first_name = first_name_field_element.get_attribute("defaultValue")
    assert attribute_first_name == '!'
    save_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//body/div[@id='root']/main[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/form[1]/div[3]/div[1]/div[1]/div[1]/div[1]/button[1]")))
    save_btn.click()
    time.sleep(3)
    my_driver.close()
    my_driver.quit()


####test-1.1.6
def test_login_proccess_edit_last_name_1_1_6():
    my_driver = driver_set()
    my_driver.get("https://portal-dev.safsarglobal.link/")
    login_header_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.LINK_TEXT, "התחברות")))
    time.sleep(2)
    login_header_element.click()
    phone_num_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.NAME, "phone")))
    phone_num_field_element.send_keys('0544803749')
    time.sleep(1)
    login_btn_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//button[contains(text(),'כניסה')]")))
    login_btn_element.click()
    WebDriverWait(my_driver, 30).until(EC.url_to_be("https://portal-dev.safsarglobal.link/"))
    time.sleep(5)
    my_account_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="root"]/div[1]/div/nav/div[1]/ul/button')))
    my_account_btn.click()
    time.sleep(2)
    edit_profile_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="rc-tabs-0-panel-tab1"]/div/div[1]/button')))
    edit_profile_btn.click()
    last_name_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="lastName"]')))
    last_name_field_element.send_keys(Keys.CONTROL + 'a')
    last_name_field_element.send_keys(Keys.BACKSPACE)
    time.sleep(2)
    last_name_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="lastName"]')))
    last_name_field_element.send_keys("6")
    time.sleep(5)
    attribute_last_name = last_name_field_element.get_attribute("defaultValue")
    assert attribute_last_name == '6'
    save_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//body/div[@id='root']/main[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/form[1]/div[3]/div[1]/div[1]/div[1]/div[1]/button[1]")))
    save_btn.click()
    time.sleep(3)
    my_driver.close()
    my_driver.quit()

###test-1.1.7
def test_login_proccess_edit_last_name_1_1_7():
    my_driver = driver_set()
    my_driver.get("https://portal-dev.safsarglobal.link/")
    login_header_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.LINK_TEXT, "התחברות")))
    time.sleep(2)
    login_header_element.click()
    phone_num_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.NAME, "phone")))
    phone_num_field_element.send_keys('0544803749')
    time.sleep(1)
    login_btn_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//button[contains(text(),'כניסה')]")))
    login_btn_element.click()
    WebDriverWait(my_driver, 30).until(EC.url_to_be("https://portal-dev.safsarglobal.link/"))
    time.sleep(5)
    my_account_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="root"]/div[1]/div/nav/div[1]/ul/button')))
    my_account_btn.click()
    time.sleep(2)
    edit_profile_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="rc-tabs-0-panel-tab1"]/div/div[1]/button')))
    edit_profile_btn.click()
    last_name_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="lastName"]')))
    last_name_field_element.send_keys(Keys.CONTROL + 'a')
    last_name_field_element.send_keys(Keys.BACKSPACE)
    time.sleep(2)
    last_name_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="lastName"]')))
    last_name_field_element.send_keys("%")
    time.sleep(5)
    attribute_last_name = last_name_field_element.get_attribute("defaultValue")
    assert attribute_last_name == '%'
    save_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//body/div[@id='root']/main[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/form[1]/div[3]/div[1]/div[1]/div[1]/div[1]/button[1]")))
    save_btn.click()
    time.sleep(3)
    my_driver.close()
    my_driver.quit()

####test-1.1.8
def test_login_proccess_edit_email_1_1_8():
    my_driver = driver_set()
    my_driver.get("https://portal-dev.safsarglobal.link/")
    login_header_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.LINK_TEXT, "התחברות")))
    time.sleep(2)
    login_header_element.click()
    phone_num_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.NAME, "phone")))
    phone_num_field_element.send_keys('0544803749')
    time.sleep(1)
    login_btn_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//button[contains(text(),'כניסה')]")))
    login_btn_element.click()
    WebDriverWait(my_driver, 30).until(EC.url_to_be("https://portal-dev.safsarglobal.link/"))
    time.sleep(5)
    my_account_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="root"]/div[1]/div/nav/div[1]/ul/button')))
    my_account_btn.click()
    time.sleep(2)
    edit_profile_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="rc-tabs-0-panel-tab1"]/div/div[1]/button')))
    edit_profile_btn.click()
    email_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="email"]')))
    email_field_element.send_keys(Keys.CONTROL + 'a')
    email_field_element.send_keys(Keys.BACKSPACE)
    time.sleep(2)
    email_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="email"]')))
    email_field_element.send_keys("jogog92125artgulin.com")
    time.sleep(5)
    attribute_email = email_field_element.get_attribute("defaultValue")
    assert  attribute_email  == "jogog92125artgulin.com"
    save_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//body/div[@id='root']/main[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/form[1]/div[3]/div[1]/div[1]/div[1]/div[1]/button[1]")))
    save_btn.click()
    time.sleep(3)
    my_driver.close()
    my_driver.quit()

####test-1.1.9
def test_login_proccess_edit_email_1_1_9():
    my_driver = driver_set()
    my_driver.get("https://portal-dev.safsarglobal.link/")
    login_header_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.LINK_TEXT, "התחברות")))
    time.sleep(2)
    login_header_element.click()
    phone_num_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.NAME, "phone")))
    phone_num_field_element.send_keys('0544803749')
    time.sleep(1)
    login_btn_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//button[contains(text(),'כניסה')]")))
    login_btn_element.click()
    WebDriverWait(my_driver, 30).until(EC.url_to_be("https://portal-dev.safsarglobal.link/"))
    time.sleep(5)
    my_account_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="root"]/div[1]/div/nav/div[1]/ul/button')))
    my_account_btn.click()
    time.sleep(2)
    edit_profile_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="rc-tabs-0-panel-tab1"]/div/div[1]/button')))
    edit_profile_btn.click()
    email_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="email"]')))
    email_field_element.send_keys(Keys.CONTROL + 'a')
    email_field_element.send_keys(Keys.BACKSPACE)
    time.sleep(2)
    email_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="email"]')))
    email_field_element.send_keys("jogog92125@.com")
    time.sleep(5)
    attribute_email = email_field_element.get_attribute("defaultValue")
    assert  attribute_email  == "jogog92125@.com"
    save_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//body/div[@id='root']/main[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/form[1]/div[3]/div[1]/div[1]/div[1]/div[1]/button[1]")))
    save_btn.click()
    time.sleep(3)
    my_driver.close()
    my_driver.quit()

###test-1.1.10
def test_login_proccess_edit_email_1_1_10():
    my_driver = driver_set()
    my_driver.get("https://portal-dev.safsarglobal.link/")
    login_header_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.LINK_TEXT, "התחברות")))
    time.sleep(2)
    login_header_element.click()
    phone_num_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.NAME, "phone")))
    phone_num_field_element.send_keys('0544803749')
    time.sleep(1)
    login_btn_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//button[contains(text(),'כניסה')]")))
    login_btn_element.click()
    WebDriverWait(my_driver, 30).until(EC.url_to_be("https://portal-dev.safsarglobal.link/"))
    time.sleep(5)
    my_account_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="root"]/div[1]/div/nav/div[1]/ul/button')))
    my_account_btn.click()
    time.sleep(2)
    edit_profile_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="rc-tabs-0-panel-tab1"]/div/div[1]/button')))
    edit_profile_btn.click()
    email_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="email"]')))
    email_field_element.send_keys(Keys.CONTROL + 'a')
    email_field_element.send_keys(Keys.BACKSPACE)
    time.sleep(2)
    email_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="email"]')))
    email_field_element.send_keys("jogog92125@artgulin")
    time.sleep(5)
    attribute_email = email_field_element.get_attribute("defaultValue")
    assert  attribute_email  == "jogog92125@artgulin"
    save_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//body/div[@id='root']/main[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/form[1]/div[3]/div[1]/div[1]/div[1]/div[1]/button[1]")))
    save_btn.click()
    time.sleep(3)
    my_driver.close()
    my_driver.quit()


###test-1.1.11
def test_login_proccess_edit_email_1_1_11():
    my_driver = driver_set()
    my_driver.get("https://portal-dev.safsarglobal.link/")
    login_header_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.LINK_TEXT, "התחברות")))
    time.sleep(2)
    login_header_element.click()
    phone_num_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.NAME, "phone")))
    phone_num_field_element.send_keys('0544803749')
    time.sleep(1)
    login_btn_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//button[contains(text(),'כניסה')]")))
    login_btn_element.click()
    WebDriverWait(my_driver, 30).until(EC.url_to_be("https://portal-dev.safsarglobal.link/"))
    time.sleep(5)
    my_account_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="root"]/div[1]/div/nav/div[1]/ul/button')))
    my_account_btn.click()
    time.sleep(2)
    edit_profile_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="rc-tabs-0-panel-tab1"]/div/div[1]/button')))
    edit_profile_btn.click()
    email_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="email"]')))
    email_field_element.send_keys(Keys.CONTROL + 'a')
    email_field_element.send_keys(Keys.BACKSPACE)
    time.sleep(2)
    email_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="email"]')))
    email_field_element.send_keys(" ")
    time.sleep(5)
    attribute_email = email_field_element.get_attribute("defaultValue")
    assert attribute_email == " "
    save_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//body/div[@id='root']/main[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/form[1]/div[3]/div[1]/div[1]/div[1]/div[1]/button[1]")))
    save_btn.click()
    time.sleep(3)
    my_driver.close()
    my_driver.quit()


###test-1.1.12
def test_login_proccess_edit_email_1_1_12():
    my_driver = driver_set()
    my_driver.get("https://portal-dev.safsarglobal.link/")
    login_header_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.LINK_TEXT, "התחברות")))
    time.sleep(2)
    login_header_element.click()
    phone_num_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.NAME, "phone")))
    phone_num_field_element.send_keys('0544803749')
    time.sleep(1)
    login_btn_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//button[contains(text(),'כניסה')]")))
    login_btn_element.click()
    WebDriverWait(my_driver, 30).until(EC.url_to_be("https://portal-dev.safsarglobal.link/"))
    time.sleep(5)
    my_account_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="root"]/div[1]/div/nav/div[1]/ul/button')))
    my_account_btn.click()
    time.sleep(2)
    edit_profile_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="rc-tabs-0-panel-tab1"]/div/div[1]/button')))
    edit_profile_btn.click()
    email_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="email"]')))
    email_field_element.send_keys(Keys.CONTROL + 'a')
    email_field_element.send_keys(Keys.BACKSPACE)
    time.sleep(2)
    email_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="email"]')))
    email_field_element.send_keys("jogog92125@artgulin .com")
    time.sleep(5)
    attribute_email = email_field_element.get_attribute("defaultValue")
    assert attribute_email == "jogog92125@artgulin .com"
    save_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//body/div[@id='root']/main[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/form[1]/div[3]/div[1]/div[1]/div[1]/div[1]/button[1]")))
    save_btn.click()
    time.sleep(3)
    my_driver.close()
    my_driver.quit()

###test-1.1.13
def test_login_proccess_edit_email_1_1_13():
    my_driver = driver_set()
    my_driver.get("https://portal-dev.safsarglobal.link/")
    login_header_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.LINK_TEXT, "התחברות")))
    time.sleep(2)
    login_header_element.click()
    phone_num_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.NAME, "phone")))
    phone_num_field_element.send_keys('0544803749')
    time.sleep(1)
    login_btn_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//button[contains(text(),'כניסה')]")))
    login_btn_element.click()
    WebDriverWait(my_driver, 30).until(EC.url_to_be("https://portal-dev.safsarglobal.link/"))
    time.sleep(5)
    my_account_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="root"]/div[1]/div/nav/div[1]/ul/button')))
    my_account_btn.click()
    time.sleep(2)
    edit_profile_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="rc-tabs-0-panel-tab1"]/div/div[1]/button')))
    edit_profile_btn.click()
    email_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="email"]')))
    email_field_element.send_keys(Keys.CONTROL + 'a')
    email_field_element.send_keys(Keys.BACKSPACE)
    time.sleep(2)
    email_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="email"]')))
    email_field_element.send_keys("@artgulin .com")
    time.sleep(5)
    attribute_email = email_field_element.get_attribute("defaultValue")
    assert attribute_email == "@artgulin .com"
    save_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//body/div[@id='root']/main[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/form[1]/div[3]/div[1]/div[1]/div[1]/div[1]/button[1]")))
    save_btn.click()
    time.sleep(3)
    my_driver.close()
    my_driver.quit()


###test-1.2.1
def test_login_proccess_edit_phone_number_1_2_1():
    my_driver = driver_set()
    my_driver.get("https://portal-dev.safsarglobal.link/")
    login_header_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.LINK_TEXT, "התחברות")))
    time.sleep(2)
    login_header_element.click()
    phone_num_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.NAME, "phone")))
    phone_num_field_element.send_keys('0544803749')
    time.sleep(1)
    login_btn_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//button[contains(text(),'כניסה')]")))
    login_btn_element.click()
    WebDriverWait(my_driver, 30).until(EC.url_to_be("https://portal-dev.safsarglobal.link/"))
    time.sleep(5)
    my_account_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="root"]/div[1]/div/nav/div[1]/ul/button')))
    my_account_btn.click()
    time.sleep(2)
    edit_phone_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="rc-tabs-0-panel-tab1"]/div/div[2]/button')))
    edit_phone_btn.click()
    time.sleep(5)
    phone_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="phone"]')))
    phone_field_element.send_keys(Keys.CONTROL + 'a')
    phone_field_element.send_keys(Keys.BACKSPACE)
    time.sleep(2)
    phone_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="phone"]')))
    phone_field_element.send_keys("0544803749")
    time.sleep(3)
    attribute_phone = phone_field_element.get_attribute("defaultValue")
    assert attribute_phone == '0544803749'
    save_phone_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="rc-tabs-0-panel-tab1"]/div/div[2]/form/button')))
    save_phone_btn.click()
    time.sleep(3)
    my_driver.close()
    my_driver.quit()


###test-1.2.2
def test_login_proccess_edit_phone_number_1_2_2():
    my_driver = driver_set()
    my_driver.get("https://portal-dev.safsarglobal.link/")
    login_header_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.LINK_TEXT, "התחברות")))
    time.sleep(2)
    login_header_element.click()
    phone_num_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.NAME, "phone")))
    phone_num_field_element.send_keys('0544803749')
    time.sleep(1)
    login_btn_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//button[contains(text(),'כניסה')]")))
    login_btn_element.click()
    WebDriverWait(my_driver, 30).until(EC.url_to_be("https://portal-dev.safsarglobal.link/"))
    time.sleep(5)
    my_account_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="root"]/div[1]/div/nav/div[1]/ul/button')))
    my_account_btn.click()
    time.sleep(2)
    edit_phone_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="rc-tabs-0-panel-tab1"]/div/div[2]/button')))
    edit_phone_btn.click()
    time.sleep(5)
    phone_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="phone"]')))
    phone_field_element.send_keys(Keys.CONTROL + 'a')
    phone_field_element.send_keys(Keys.BACKSPACE)
    time.sleep(2)
    phone_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="phone"]')))
    phone_field_element.send_keys("ALMA")
    time.sleep(3)
    attribute_phone = phone_field_element.get_attribute("defaultValue")
    assert attribute_phone == 'ALMA'
    save_phone_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="rc-tabs-0-panel-tab1"]/div/div[2]/form/button')))
    save_phone_btn.click()
    time.sleep(3)
    my_driver.close()
    my_driver.quit()


###test-1.2.3
def test_login_proccess_edit_phone_number_1_2_3():
    my_driver = driver_set()
    my_driver.get("https://portal-dev.safsarglobal.link/")
    login_header_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.LINK_TEXT, "התחברות")))
    time.sleep(2)
    login_header_element.click()
    phone_num_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.NAME, "phone")))
    phone_num_field_element.send_keys('0544803749')
    time.sleep(1)
    login_btn_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, "//button[contains(text(),'כניסה')]")))
    login_btn_element.click()
    WebDriverWait(my_driver, 30).until(EC.url_to_be("https://portal-dev.safsarglobal.link/"))
    time.sleep(5)
    my_account_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="root"]/div[1]/div/nav/div[1]/ul/button')))
    my_account_btn.click()
    time.sleep(2)
    edit_phone_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="rc-tabs-0-panel-tab1"]/div/div[2]/button')))
    edit_phone_btn.click()
    time.sleep(5)
    phone_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="phone"]')))
    phone_field_element.send_keys(Keys.CONTROL + 'a')
    phone_field_element.send_keys(Keys.BACKSPACE)
    time.sleep(2)
    phone_field_element = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="phone"]')))
    phone_field_element.send_keys("!@#$")
    time.sleep(3)
    attribute_phone = phone_field_element.get_attribute("defaultValue")
    assert attribute_phone == '!@#$'
    save_phone_btn = WebDriverWait(my_driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="rc-tabs-0-panel-tab1"]/div/div[2]/form/button')))
    save_phone_btn.click()
    time.sleep(3)
    my_driver.close()
    my_driver.quit()